POST http://localhost:8080/api/protein/amount
Content-Type: text/plain

How much protein is there in chicken?

#####
POST http://localhost:8080/api/protein/amount
Content-Type: text/plain

I am talking about "Chicken, leg, meat and skin, raw"